export const IMPORT_ADDRESS = "IMPORT_ADDRESS";
export const REMOVE_ADDRESS = "REMOVE_ADDRESS";
export const SET_ADDRESSES = "SET_ADDRESSES";
export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
